name: Blog Posts

on:
  # schedule:
  #   - cron: 0 2 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: "Update this repo's README with latest blog posts"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in capawesome.io posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://capawesome.io/feed_rss_created.xml"
          readme_path: "./profile/README.md"
